create table "public"."user_data" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "data" json
);


CREATE UNIQUE INDEX user_data_id_key ON public.user_data USING btree (id);

CREATE UNIQUE INDEX user_data_pkey ON public.user_data USING btree (id);

CREATE UNIQUE INDEX user_data_user_id_key ON public.user_data USING btree (user_id);

alter table "public"."user_data" add constraint "user_data_pkey" PRIMARY KEY using index "user_data_pkey";

alter table "public"."user_data" add constraint "public_user_data_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."user_data" validate constraint "public_user_data_user_id_fkey";

alter table "public"."user_data" add constraint "user_data_id_key" UNIQUE using index "user_data_id_key";

alter table "public"."user_data" add constraint "user_data_user_id_key" UNIQUE using index "user_data_user_id_key";

grant delete on table "public"."user_data" to "anon";

grant insert on table "public"."user_data" to "anon";

grant references on table "public"."user_data" to "anon";

grant select on table "public"."user_data" to "anon";

grant trigger on table "public"."user_data" to "anon";

grant truncate on table "public"."user_data" to "anon";

grant update on table "public"."user_data" to "anon";

grant delete on table "public"."user_data" to "authenticated";

grant insert on table "public"."user_data" to "authenticated";

grant references on table "public"."user_data" to "authenticated";

grant select on table "public"."user_data" to "authenticated";

grant trigger on table "public"."user_data" to "authenticated";

grant truncate on table "public"."user_data" to "authenticated";

grant update on table "public"."user_data" to "authenticated";

grant delete on table "public"."user_data" to "service_role";

grant insert on table "public"."user_data" to "service_role";

grant references on table "public"."user_data" to "service_role";

grant select on table "public"."user_data" to "service_role";

grant trigger on table "public"."user_data" to "service_role";

grant truncate on table "public"."user_data" to "service_role";

grant update on table "public"."user_data" to "service_role";


